name: Mirror to GitLab

on:
  push:
    branches: ["*"]  # jeder Push auf jedem Branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "info@ilmenauer-schachverein.de"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.erik-skopp.de/chess/SimpleDWZ.git
          git push gitlab --all
          git push gitlab --tags
